filetype off            " reset filetype detection for pathgen to work correctly
"call pathogen#runtime_append_all_bundles()
set nojoinspaces        " do not add two spaces after a period 
set expandtab           " ensure consistency between editors
set tabstop=4           " eight is too much, keep it short
set shiftwidth=4        " eight is too much, keep it short
set textwidth=80        " short lines too
set history=10000       " never forget
set autoindent          " make things pretty
set modelines=1         " no longer the default?
set visualbell          " don't disturb the neighbors
let g:is_bash=1         " even old-timey bourne looks awful without `is_bash`
syntax on               " colorize source

" <!--+
"     | pretty xml comments
"     +-->
au BufEnter *.xml,*.xslt,*.xsl set comments=s4:<!--,mb:=-,mb:\|,ex:-->
au BufLeave *.xml,*.xslt,*.xsl set comments=s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-
au BufRead,BufNewFile *.coffee set comments=:#
au BufRead,BufNewFile *.js set sw=4 ts=4
au BufRead,BufNewFile *.rb set sw=2 ts=2
au BufRead,BufNewFile *._coffee,*.coffee set comments=:# ft=coffee
au BufRead,BufNewFile *._js set comments=:# ft=javascript
au BufEnter rules set noet
au BufEnter Makefile set noet
au BufEnter COMMIT_EDITMSG set tw=72

" Do you remember the time you spent with Jamfiles?
au BufEnter Jamfile.v2,Jamfile,*.jam set tw=0 et

au BufEnter *.md set ft=markdown

" edit a file in the same directory as the file in the buffer
if has("unix")
    map ,e :edit <C-R>=expand("%:p:h") . "/" <CR>
    map ,s :split <C-R>=expand("%:p:h") . "/" <CR>
else
    map ,e :edit <C-R>=expand("%:p:h") . "\\" <CR>
    map ,s :split <C-R>=expand("%:p:h") . "\\" <CR>
endif

set modeline

command Ls !ls -all %
" http://stackoverflow.com/questions/2393671/vim-restores-cursor-position-exclude-special-files
autocmd BufReadPost *
   \ if line("'\"") > 0 && line("'\"") <= line("$") |
   \   exe "normal! g`\"" |
   \ endif

au BufRead,BufNewFile jquery.ui.*.js set ts=8 tw=0 noet nowrap
au BufRead,BufNewFile *.markdown,*.md set com=
