filetype off            " reset filetype detection for pathgen to work correctly
"call pathogen#runtime_append_all_bundles()
set nojoinspaces        " do not add two spaces after a period
set expandtab           " ensure consistency between editors
set tabstop=4           " eight is too much, keep it short
set shiftwidth=4        " eight is too much, keep it short
set textwidth=78        " short lines too
" there's also `viminfo` to configure.
" https://vi.stackexchange.com/questions/2920/how-to-further-increase-cmdline-history-size
set history=10000      " never forget
set autoindent          " make things pretty
set modelines=1         " no longer the default?
set visualbell          " don't disturb the neighbors
" this is on parole, let's see if we can just keep our final endings straight.
" let g:is_bash=1         " even old-timey bourne looks awful without `is_bash`
syntax on               " colorize source

" put search results in the middle of the screen
" https://vim.fandom.com/wiki/Make_search_results_appear_in_the_middle_of_the_screen
:nnoremap n nzz
:nnoremap N Nzz
:nnoremap * *zz
:nnoremap # #zz
:nnoremap g* g*zz
:nnoremap g# g#zz

" Learn VimScript the Hard Way

" Echoing Messages.
" Echo a cat on start up and store in in the messages history.

" echom ">^.^<"

" Non-Modal Mapping

" the following is not modal and will trigger in any mode
" :map - ddp

" Modal Mapping - normal mode

:nmap - ddp
:nmap _ ddkP

" Modal Mapping - insert mode

" types to `d`s in visual mode
" :imap <C-D> dd
" delete a line in insert mode, but you end up in normal mode
" :imap <C-D> <esc>dd
" delete a line in insert mode, stay in insert mode
:imap <C-x> <esc>ddi

" TODO Learn how to set settings by file type.

" <!--+
"     | pretty xml comments
"     +-->
au BufEnter *.xml,*.xslt,*.xsl set comments=s4:<!--,mb:=-,mb:\|,ex:-->
au BufLeave *.xml,*.xslt,*.xsl set comments=s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-
au BufRead,BufNewFile *.coffee set comments=:#
au BufRead,BufNewFile *.js,*.bash set sw=4 ts=4
au BufRead,BufNewFile *.tf,*.rb,*.yaml,*yml,*.cr set sw=2 ts=2
au BufRead,BufNewFile *._coffee,*.coffee set comments=:# ft=coffee
au BufRead,BufNewFile *._js set comments=:# ft=javascript
au BufEnter rules set noet
au BufEnter,BufNewFile *.go,Makefile set noet
au BufEnter COMMIT_EDITMSG set tw=72
au BufEnter PULL_REQUEST_EDITMSG set ft=markdown
au BufEnter PULL_REQUEST_EDITMSG :Goyo

" Do you remember the time you spent with Jamfiles?
au BufEnter Jamfile.v2,Jamfile,*.jam set tw=0 et

au BufEnter *.md set ft=markdown

" edit a file in the same directory as the file in the buffer
if has("unix")
    map ,e :edit <C-R>=expand("%:p:h") . "/" <CR>
    map ,s :split <C-R>=expand("%:p:h") . "/" <CR>
else
    map ,e :edit <C-R>=expand("%:p:h") . "\\" <CR>
    map ,s :split <C-R>=expand("%:p:h") . "\\" <CR>
endif

set modeline

command Ls !ls -all %
" http://stackoverflow.com/questions/2393671/vim-restores-cursor-position-exclude-special-files
autocmd BufReadPost *
   \ if line("'\"") > 0 && line("'\"") <= line("$") |
   \   exe "normal! g`\"" |
   \ endif

au BufRead,BufNewFile jquery.ui.*.js set ts=8 tw=0 noet nowrap
au BufRead,BufNewFile *.markdown,*.md set com=

" newer stuff
call plug#begin('~/.vim/plugged')

Plug 'cappyzawa/starlark.vim'
Plug 'vmware-tanzu/ytt.vim'
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/goyo.vim'
Plug 'godlygeek/tabular'
Plug 'preservim/vim-markdown'
Plug 'tommcdo/vim-lion'
"Plug 'sainnhe/vim-color-lost-shrine'
Plug 'reedes/vim-pencil'
Plug 'prurigro/vim-markdown-concealed'
Plug 'grafana/vim-alloy'
Plug 'endel/vim-github-colorscheme'
Plug 'hashivim/vim-terraform'
"Plug 'dpc/vim-smarttabs'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'roxma/nvim-yarp', { 'do': 'pip install -r requirements.txt' }
Plug 'lifepillar/pgsql.vim'
Plug 'google/vim-jsonnet'
Plug 'morhetz/gruvbox'
Plug 'grafana/vim-alloy'
Plug 'preservim/nerdtree'
Plug 'raghur/vim-ghost'

call plug#end()

" Unified color scheme (default: dark)
" colo seoul256

" Light color scheme
" colo seoul256-light

" Switch
"set background=dark
"set background=light

" Color name (:help cterm-colors) or ANSI code
let g:limelight_conceal_ctermfg = 'gray'
let g:limelight_conceal_ctermfg = 240

" Color name (:help gui-colors) or RGB color
let g:limelight_conceal_guifg = 'DarkGray'
let g:limelight_conceal_guifg = '#777777'

function! s:goyo_enter()
    silent !tmux set status off
    silent !tmux list-panes -F '\#F' | grep -q Z || tmux resize-pane -Z
    "Limelight
    PencilOff
    PencilSoft
    "set linebreak
    "set tw=0
    colo seoul256-light
endfunction

function! s:goyo_leave()
    silent !tmux set status on
    silent !tmux list-panes -F '\#F' | grep -q Z && tmux resize-pane -Z
    "Limelight!
    PencilOff
    "set nolinebreak
    "set tw=72
    colo default
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()

filetype plugin indent off

" Wrap only comments, not code.
au BufEnter,BufNewFile *.py,*.html,*.js set formatoptions-=t
au BufLeave *.py,*.html,*.js set formatoptions+=t

au BufEnter,BufNewFile *.ytt.yaml EnableYtt
au BufEnter,BufNewFile *.ytt.yaml set comments=b:#!
au BufLeave *.ytt.yaml DisableYtt

" Sets the wrap for comments based on the indent. If the indent is small the
" comments wrap at the same left margin. If it is large we allow the comments to
" have a minimum width.
fun! PrettyRobotsCommentate ()
    if &textwidth != 0
        let currentLine = getline('.')
        let spaces = strlen(matchstr(getline('.'), '^ \+'))
        if spaces > 12
            let textwidth = 80 - 12 + spaces
        else
            let textwidth = 80
        end
        let &textwidth = textwidth
    end
endf

autocmd CursorMoved *.py,*.html,*.js,*.alloy :call PrettyRobotsCommentate()
autocmd FileType python,html,javascript,sh,bash,zsh,alloy autocmd! CursorMoved <buffer> :call PrettyRobotsCommentate()

" Without this C99 compound literals do not highlight correctly.
let c_no_curly_error=1

autocmd BufEnter * :syntax sync fromstart
