#!/bin/sh

red="\033[1;31m"
color_end="\033[0m"

# Check unwanted trailing whitespace or space/tab indents;

if [ "x`git diff --cached --check`" != "x" ]; then
    echo -e ${red}Commit failed${color_end}
    git diff --cached --check
    exit 1
fi
