#!/usr/bin/env zsh

function errf {
    printf "$@"
    print --
}

# https://unix.stackexchange.com/questions/706897/exporting-zsh-history-separated-by-0-characters-instead-of-n

function {
    (( $# )) || { errf 'save, list or fu name'; return 1 }
    case "$1" in
        save )
            shift 
            name=$1 
            shift
            typeset key=$(fc -l | cut -d' ' -f 1 | tail -n 1)
            print "$key"
            print -- "--- saved as ~/.dotfiles/fu/$name ---"
            print -R "${history[$key]}" | tee ~/.dotfiles/fu/"$name"
            return 1
            ;;
        list )
            shift 
            ls ~/.dotfiles/fu
            ;;
        * )
            name=$1 
            shift
            [[ -f ~/.dotfiles/fu/"$name" ]] || { errf 'not defined: %s' "$name"; return 1 }
            print -RS "$(<~/.dotfiles/fu/"$name")"
            ;;
    esac
} "$@"
